//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedicinePlanner.Core.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MessagesResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MessagesResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MedicinePlanner.Core.Resources.MessagesResource", typeof(MessagesResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access denied! Please, log in again!.
        /// </summary>
        public static string ACCESS_DENIED {
            get {
                return ResourceManager.GetString("ACCESS_DENIED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This food relation already exists!.
        /// </summary>
        public static string FOOD_RELATION_ALREADY_EXISTS {
            get {
                return ResourceManager.GetString("FOOD_RELATION_ALREADY_EXISTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This food relation cannot be deleted!.
        /// </summary>
        public static string FOOD_RELATION_NOT_DELETABLE {
            get {
                return ResourceManager.GetString("FOOD_RELATION_NOT_DELETABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This food relation cannot be modified!.
        /// </summary>
        public static string FOOD_RELATION_NOT_EDITABLE {
            get {
                return ResourceManager.GetString("FOOD_RELATION_NOT_EDITABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Food relation not found!.
        /// </summary>
        public static string FOOD_RELATION_NOT_FOUND {
            get {
                return ResourceManager.GetString("FOOD_RELATION_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Food schedule not found!.
        /// </summary>
        public static string FOOD_SCHEDULE_NOT_FOUND {
            get {
                return ResourceManager.GetString("FOOD_SCHEDULE_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meal time.
        /// </summary>
        public static string MEAL_TIME {
            get {
                return ResourceManager.GetString("MEAL_TIME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medicine with such parameters already exists!.
        /// </summary>
        public static string MEDICINE_ALREADY_EXISTS {
            get {
                return ResourceManager.GetString("MEDICINE_ALREADY_EXISTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This medicine cannot be modified!.
        /// </summary>
        public static string MEDICINE_NOT_EDITABLE {
            get {
                return ResourceManager.GetString("MEDICINE_NOT_EDITABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medicine not found!.
        /// </summary>
        public static string MEDICINE_NOT_FOUND {
            get {
                return ResourceManager.GetString("MEDICINE_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medicine schedule not found!.
        /// </summary>
        public static string MEDICINE_SCHEDULE_NOT_FOUND {
            get {
                return ResourceManager.GetString("MEDICINE_SCHEDULE_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medicine schedules for {0} overlap!.
        /// </summary>
        public static string MEDICINE_SCHEDULES_OVERLAP {
            get {
                return ResourceManager.GetString("MEDICINE_SCHEDULES_OVERLAP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please correct the errors in input data and try again!.
        /// </summary>
        public static string MODEL_VALIDATION_ERROR {
            get {
                return ResourceManager.GetString("MODEL_VALIDATION_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This pharmaceutical form already exists!.
        /// </summary>
        public static string PHARMACEUTICAL_FORM_ALREADY_EXISTS {
            get {
                return ResourceManager.GetString("PHARMACEUTICAL_FORM_ALREADY_EXISTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This pharmaceutical form cannot be deleted!.
        /// </summary>
        public static string PHARMACEUTICAL_FORM_NOT_DELETABLE {
            get {
                return ResourceManager.GetString("PHARMACEUTICAL_FORM_NOT_DELETABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This pharmaceutical form cannot be modified!.
        /// </summary>
        public static string PHARMACEUTICAL_FORM_NOT_EDITABLE {
            get {
                return ResourceManager.GetString("PHARMACEUTICAL_FORM_NOT_EDITABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pharmaceutical form not found!.
        /// </summary>
        public static string PHARMACEUTICAL_FORM_NOT_FOUND {
            get {
                return ResourceManager.GetString("PHARMACEUTICAL_FORM_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation successful!.
        /// </summary>
        public static string SUCCESS_MESSAGE {
            get {
                return ResourceManager.GetString("SUCCESS_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Take {0}, {1}, D: {2}, {3}.
        /// </summary>
        public static string TAKE_DESCRIPTION {
            get {
                return ResourceManager.GetString("TAKE_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong! Please, try again!.
        /// </summary>
        public static string UNHANDLED_ERROR {
            get {
                return ResourceManager.GetString("UNHANDLED_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This user already exists!.
        /// </summary>
        public static string USER_ALREADY_EXISTS {
            get {
                return ResourceManager.GetString("USER_ALREADY_EXISTS", resourceCulture);
            }
        }
    }
}
